/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as CheckoutPlanIdRouteImport } from './routes/checkout.$planId'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as DashboardCareersRouteImport } from './routes/dashboard/careers'
import { Route as DashboardEditaisRouteImport } from './routes/dashboard/editais'
import { Route as DashboardErrorsRouteImport } from './routes/dashboard/errors'
import { Route as DashboardEssaysRouteImport } from './routes/dashboard/essays'
import { Route as DashboardHistoryRouteImport } from './routes/dashboard/history'
import { Route as DashboardMockExamsRouteImport } from './routes/dashboard/mock-exams'
import { Route as DashboardMyContestRouteImport } from './routes/dashboard/my-contest'
import { Route as DashboardNotebooksRouteImport } from './routes/dashboard/notebooks'
import { Route as DashboardPerformanceRouteImport } from './routes/dashboard/performance'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardQuestionBankRouteImport } from './routes/dashboard/question-bank'
import { Route as DashboardQuestionsRouteImport } from './routes/dashboard/questions'
import { Route as DashboardStudentExamsRouteImport } from './routes/dashboard/student-exams'
import { Route as DashboardStudyPlanRouteImport } from './routes/dashboard/study-plan'
import { Route as DashboardStudyToolsRouteImport } from './routes/dashboard/study-tools'
import { Route as DashboardTimerRouteImport } from './routes/dashboard/timer'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPlanIdRoute = CheckoutPlanIdRouteImport.update({
  id: '/checkout/$planId',
  path: '/checkout/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCareersRoute = DashboardCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEditaisRoute = DashboardEditaisRouteImport.update({
  id: '/editais',
  path: '/editais',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardErrorsRoute = DashboardErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEssaysRoute = DashboardEssaysRouteImport.update({
  id: '/essays',
  path: '/essays',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMockExamsRoute = DashboardMockExamsRouteImport.update({
  id: '/mock-exams',
  path: '/mock-exams',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMyContestRoute = DashboardMyContestRouteImport.update({
  id: '/my-contest',
  path: '/my-contest',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotebooksRoute = DashboardNotebooksRouteImport.update({
  id: '/notebooks',
  path: '/notebooks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPerformanceRoute = DashboardPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQuestionBankRoute = DashboardQuestionBankRouteImport.update({
  id: '/question-bank',
  path: '/question-bank',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQuestionsRoute = DashboardQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStudentExamsRoute = DashboardStudentExamsRouteImport.update({
  id: '/student-exams',
  path: '/student-exams',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStudyPlanRoute = DashboardStudyPlanRouteImport.update({
  id: '/study-plan',
  path: '/study-plan',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStudyToolsRoute = DashboardStudyToolsRouteImport.update({
  id: '/study-tools',
  path: '/study-tools',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTimerRoute = DashboardTimerRouteImport.update({
  id: '/timer',
  path: '/timer',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/careers': typeof DashboardCareersRoute
  '/dashboard/editais': typeof DashboardEditaisRoute
  '/dashboard/errors': typeof DashboardErrorsRoute
  '/dashboard/essays': typeof DashboardEssaysRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/mock-exams': typeof DashboardMockExamsRoute
  '/dashboard/my-contest': typeof DashboardMyContestRoute
  '/dashboard/notebooks': typeof DashboardNotebooksRoute
  '/dashboard/performance': typeof DashboardPerformanceRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/question-bank': typeof DashboardQuestionBankRoute
  '/dashboard/questions': typeof DashboardQuestionsRoute
  '/dashboard/student-exams': typeof DashboardStudentExamsRoute
  '/dashboard/study-plan': typeof DashboardStudyPlanRoute
  '/dashboard/study-tools': typeof DashboardStudyToolsRoute
  '/dashboard/timer': typeof DashboardTimerRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/careers': typeof DashboardCareersRoute
  '/dashboard/editais': typeof DashboardEditaisRoute
  '/dashboard/errors': typeof DashboardErrorsRoute
  '/dashboard/essays': typeof DashboardEssaysRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/mock-exams': typeof DashboardMockExamsRoute
  '/dashboard/my-contest': typeof DashboardMyContestRoute
  '/dashboard/notebooks': typeof DashboardNotebooksRoute
  '/dashboard/performance': typeof DashboardPerformanceRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/question-bank': typeof DashboardQuestionBankRoute
  '/dashboard/questions': typeof DashboardQuestionsRoute
  '/dashboard/student-exams': typeof DashboardStudentExamsRoute
  '/dashboard/study-plan': typeof DashboardStudyPlanRoute
  '/dashboard/study-tools': typeof DashboardStudyToolsRoute
  '/dashboard/timer': typeof DashboardTimerRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/careers': typeof DashboardCareersRoute
  '/dashboard/editais': typeof DashboardEditaisRoute
  '/dashboard/errors': typeof DashboardErrorsRoute
  '/dashboard/essays': typeof DashboardEssaysRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/mock-exams': typeof DashboardMockExamsRoute
  '/dashboard/my-contest': typeof DashboardMyContestRoute
  '/dashboard/notebooks': typeof DashboardNotebooksRoute
  '/dashboard/performance': typeof DashboardPerformanceRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/question-bank': typeof DashboardQuestionBankRoute
  '/dashboard/questions': typeof DashboardQuestionsRoute
  '/dashboard/student-exams': typeof DashboardStudentExamsRoute
  '/dashboard/study-plan': typeof DashboardStudyPlanRoute
  '/dashboard/study-tools': typeof DashboardStudyToolsRoute
  '/dashboard/timer': typeof DashboardTimerRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/privacy'
    | '/terms'
    | '/checkout/$planId'
    | '/dashboard/admin'
    | '/dashboard/careers'
    | '/dashboard/editais'
    | '/dashboard/errors'
    | '/dashboard/essays'
    | '/dashboard/history'
    | '/dashboard/mock-exams'
    | '/dashboard/my-contest'
    | '/dashboard/notebooks'
    | '/dashboard/performance'
    | '/dashboard/profile'
    | '/dashboard/question-bank'
    | '/dashboard/questions'
    | '/dashboard/student-exams'
    | '/dashboard/study-plan'
    | '/dashboard/study-tools'
    | '/dashboard/timer'
    | '/dashboard/'
    | '/api/public/stripe-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy'
    | '/terms'
    | '/checkout/$planId'
    | '/dashboard/admin'
    | '/dashboard/careers'
    | '/dashboard/editais'
    | '/dashboard/errors'
    | '/dashboard/essays'
    | '/dashboard/history'
    | '/dashboard/mock-exams'
    | '/dashboard/my-contest'
    | '/dashboard/notebooks'
    | '/dashboard/performance'
    | '/dashboard/profile'
    | '/dashboard/question-bank'
    | '/dashboard/questions'
    | '/dashboard/student-exams'
    | '/dashboard/study-plan'
    | '/dashboard/study-tools'
    | '/dashboard/timer'
    | '/dashboard'
    | '/api/public/stripe-webhook'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/privacy'
    | '/terms'
    | '/checkout/$planId'
    | '/dashboard/admin'
    | '/dashboard/careers'
    | '/dashboard/editais'
    | '/dashboard/errors'
    | '/dashboard/essays'
    | '/dashboard/history'
    | '/dashboard/mock-exams'
    | '/dashboard/my-contest'
    | '/dashboard/notebooks'
    | '/dashboard/performance'
    | '/dashboard/profile'
    | '/dashboard/question-bank'
    | '/dashboard/questions'
    | '/dashboard/student-exams'
    | '/dashboard/study-plan'
    | '/dashboard/study-tools'
    | '/dashboard/timer'
    | '/dashboard/'
    | '/api/public/stripe-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  CheckoutPlanIdRoute: typeof CheckoutPlanIdRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$planId': {
      id: '/checkout/$planId'
      path: '/checkout/$planId'
      fullPath: '/checkout/$planId'
      preLoaderRoute: typeof CheckoutPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/careers': {
      id: '/dashboard/careers'
      path: '/careers'
      fullPath: '/dashboard/careers'
      preLoaderRoute: typeof DashboardCareersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/editais': {
      id: '/dashboard/editais'
      path: '/editais'
      fullPath: '/dashboard/editais'
      preLoaderRoute: typeof DashboardEditaisRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/errors': {
      id: '/dashboard/errors'
      path: '/errors'
      fullPath: '/dashboard/errors'
      preLoaderRoute: typeof DashboardErrorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/essays': {
      id: '/dashboard/essays'
      path: '/essays'
      fullPath: '/dashboard/essays'
      preLoaderRoute: typeof DashboardEssaysRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/history': {
      id: '/dashboard/history'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/mock-exams': {
      id: '/dashboard/mock-exams'
      path: '/mock-exams'
      fullPath: '/dashboard/mock-exams'
      preLoaderRoute: typeof DashboardMockExamsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/my-contest': {
      id: '/dashboard/my-contest'
      path: '/my-contest'
      fullPath: '/dashboard/my-contest'
      preLoaderRoute: typeof DashboardMyContestRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notebooks': {
      id: '/dashboard/notebooks'
      path: '/notebooks'
      fullPath: '/dashboard/notebooks'
      preLoaderRoute: typeof DashboardNotebooksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/performance': {
      id: '/dashboard/performance'
      path: '/performance'
      fullPath: '/dashboard/performance'
      preLoaderRoute: typeof DashboardPerformanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/question-bank': {
      id: '/dashboard/question-bank'
      path: '/question-bank'
      fullPath: '/dashboard/question-bank'
      preLoaderRoute: typeof DashboardQuestionBankRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/questions': {
      id: '/dashboard/questions'
      path: '/questions'
      fullPath: '/dashboard/questions'
      preLoaderRoute: typeof DashboardQuestionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/student-exams': {
      id: '/dashboard/student-exams'
      path: '/student-exams'
      fullPath: '/dashboard/student-exams'
      preLoaderRoute: typeof DashboardStudentExamsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/study-plan': {
      id: '/dashboard/study-plan'
      path: '/study-plan'
      fullPath: '/dashboard/study-plan'
      preLoaderRoute: typeof DashboardStudyPlanRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/study-tools': {
      id: '/dashboard/study-tools'
      path: '/study-tools'
      fullPath: '/dashboard/study-tools'
      preLoaderRoute: typeof DashboardStudyToolsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/timer': {
      id: '/dashboard/timer'
      path: '/timer'
      fullPath: '/dashboard/timer'
      preLoaderRoute: typeof DashboardTimerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardCareersRoute: typeof DashboardCareersRoute
  DashboardEditaisRoute: typeof DashboardEditaisRoute
  DashboardErrorsRoute: typeof DashboardErrorsRoute
  DashboardEssaysRoute: typeof DashboardEssaysRoute
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardMockExamsRoute: typeof DashboardMockExamsRoute
  DashboardMyContestRoute: typeof DashboardMyContestRoute
  DashboardNotebooksRoute: typeof DashboardNotebooksRoute
  DashboardPerformanceRoute: typeof DashboardPerformanceRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardQuestionBankRoute: typeof DashboardQuestionBankRoute
  DashboardQuestionsRoute: typeof DashboardQuestionsRoute
  DashboardStudentExamsRoute: typeof DashboardStudentExamsRoute
  DashboardStudyPlanRoute: typeof DashboardStudyPlanRoute
  DashboardStudyToolsRoute: typeof DashboardStudyToolsRoute
  DashboardTimerRoute: typeof DashboardTimerRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardCareersRoute: DashboardCareersRoute,
  DashboardEditaisRoute: DashboardEditaisRoute,
  DashboardErrorsRoute: DashboardErrorsRoute,
  DashboardEssaysRoute: DashboardEssaysRoute,
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardMockExamsRoute: DashboardMockExamsRoute,
  DashboardMyContestRoute: DashboardMyContestRoute,
  DashboardNotebooksRoute: DashboardNotebooksRoute,
  DashboardPerformanceRoute: DashboardPerformanceRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardQuestionBankRoute: DashboardQuestionBankRoute,
  DashboardQuestionsRoute: DashboardQuestionsRoute,
  DashboardStudentExamsRoute: DashboardStudentExamsRoute,
  DashboardStudyPlanRoute: DashboardStudyPlanRoute,
  DashboardStudyToolsRoute: DashboardStudyToolsRoute,
  DashboardTimerRoute: DashboardTimerRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  CheckoutPlanIdRoute: CheckoutPlanIdRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
